# ---------- BUILD STAGE ----------
FROM node:20 AS build
WORKDIR /app

ENV ROLLUP_SKIP_NATIVE=1
ENV ESBUILD_BINARY_PATH=""

COPY package.json ./
RUN npm install

COPY . .
RUN npm run build

# ---------- RUN STAGE ----------
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
